---
abstract: 'Perl extension for grammar based parsing and transformation of data.'
author:
  - 'Tom Kirchner <tk@activestate.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-Highlife
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: 0
  File::Slurp: 0
version: 0.02
