--- #YAML:1.0
name:               Parse-Highlife
version:            0.01
abstract:           Perl extension for grammar based parsing and transformation of data.
author:
    - Tom Kirchner <tk@activestate.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:   0
    File::Slurp:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
